#!/bin/bash -e
# @installable
MYSELF="$(readlink -f "$0")"
MYDIR="${MYSELF%/*}"
ME=$(basename $MYSELF)

source $MYDIR/env
[[ -f $LOCAL_ENV ]] && source $LOCAL_ENV 
source $MYDIR/log.sh
source $MYDIR/db.sh

message="$1"
wip="${2:-true}"
detail="${3:-auto generated by gclit}"

if [[ ! -n "$(curr_branch)" ]]; then
    err "you have to be inside the repository directory"

    branchd="$(db CURR_FEATURE_DIR)"
    if [[ -d "$branchd" ]]; then
        info "maybe you want to go to $branchd?"
    fi
    exit 1
fi

name="$(db CURR_FEATURE)"
target=$TARGET_BRANCH
if [[ ! -n "$name" ]]; then
    err "you're not working on any features, make sure to start one with gclit-feature"
    exit 1
fi

info "creating request to merge back to $target ..."
git checkout $name

info "${name}'s merge request message:"
if [[ -n "$message" ]]; then
    echo "$message"
else
    read message
fi

if [[ $wip == true ]]; then
    message="[WIP] $message"
    info "WIP prefix added"
fi

# https://docs.gitlab.com/ee/user/project/push_options.html
git push \
    -o merge_request.create \
    -o merge_request.target=$target \
    -o merge_request.remove_source_branch \
    -o merge_request.title="$message" \
    -o merge_request.description="$detail"

$MYDIR/rr-comment.sh "opened merge request to $target"
